changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## dbt-core {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}} ([#{{.Custom.Issue}}](https://github.com/dbt-labs/dbt-core/issues/{{.Custom.Issue}}), [#{{.Custom.PR}}](https://github.com/dbt-labs/dbt-core/pull/{{.Custom.PR}})) ContributorData {{.Custom.Author}} {{.Custom.PR}}'
kinds:
- label: Fixes
- label: Features
- label: Under the Hood
- label: Breaking Changes
- label: Docs
- label: Dependancies
custom:
- key: Author
  label: GitHub Name
  type: string
  minLength: 3
- key: Issue
  label: GitHub Issue Number
  type: int
  minLength: 4
- key: PR
  label: GitHub Pull Request Number
  type: int
  minLength: 4
