# Configuration for pre-commit hooks (see https://pre-commit.com/).
# Eventually the hooks described here will be run as tests before merging each PR.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3
    args: [--line-length=99]
- repo: https://gitlab.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    exclude: ^test/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.782'
  hooks:
  - id: mypy
    additional_dependencies: []
