[tool.mypy]
exclude = ['core/build/.*']
files = 'core'
mypy_path = "third-party-stubs/"
namespace_packages = true

[tool.black]
# TODO: remove global exclusion of tests when testing overhaul is complete
force-exclude = 'test'
line-length = 99
target-version = ['py38']
