[tool.bumpver]
current_version = "1.4.0a1"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['current_version = "{version}"']
"core/pyproject.toml" = ["{version}"]
"core/setup.py" = ["{package_version}"]
"plugins/postgres/pyproject.toml" = ["{version}"]
"plugins/postgres/setup.py" = ["{package_version}"]
"tests/adapter/pyproject.toml" = ["{version}"]
"tests/adapter/setup.py" = ["{package_version}"]

[tool.mypy]
# TODO: widen range of files as we fix issues
files = 'core/dbt'
mypy_path = "third-party-stubs/"
namespace_packages = true

[tool.black]
# TODO: remove global exclusion of tests when testing overhaul is complete
force-exclude = "test"
line-length = 99
target-version = ["py38"]
