name: "Set up postgres (windows)"
description: "Set up postgres service on windows vm for dbt integration tests"
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        choco install postgresql16 --params "/Password:password" --ia "--enable-components server,commandlinetools --extract-only 1" --no-progress

        $Env:PG_BINDIR = cmd /c "$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe --bindir" '2>&1'
        $Env:PG_LIBDIR = cmd /c "$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe --libdir" '2>&1'

        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $env:Path += ";$env:PGBIN"
        bash ${{ github.action_path }}/setup_db.sh
