name: "Set up postgres (windows)"
description: "Set up postgres service on windows vm for dbt integration tests"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # The Windows runner has some PostgreSQL environment variables set
        # that may confuse users since they may be irrelevant to the
        # PostgreSQL server we're using. Since GitHub actions does not
        # support unsetting environment variables, the best we can do is to
        # clear their values in order to indicate they must not be used.
        # for name in "PGROOT" "PGDATA" "PGBIN" "PGUSER" "PGPASSWORD"; do
        #   echo "$name=" >> $GITHUB_ENV
        # done

        choco install postgresql16 \
          --params "/Password:password" \
          --ia "--enable-components server,commandlinetools --extract-only 1" \
          --no-progress

        PG_BINDIR="C:\Program Files\PostgreSQL\16\bin"
        PG_LIBDIR="C:\Program Files\PostgreSQL\16\lib"

        echo "$PG_BINDIR" >> $GITHUB_PATH
        echo "PQ_LIB_DIR=$PG_LIBDIR" >> $GITHUB_ENV

        PGBIN="C:\Program Files\PostgreSQL\16\bin"
        PGROOT="C:\Program Files\PostgreSQL\16"
        PGDATA="C:\Program Files\PostgreSQL\16\data"

        echo "PGBIN=$PGBIN" >> $GITHUB_ENV
        echo "PGROOT=$PGROOT" >> $GITHUB_ENV
        echo "PGDATA=$PGDATA" >> $GITHUB_ENV

        "$PGBIN\pg_ctl.exe" register -N "postgresql16" -U "NT AUTHORITY\NetworkService" -D "C:/Program Files/postgresql/pgsql/bin/pgsql/data" -w
    - shell: pwsh
      run: |
        $pgService = Get-Service -Name postgresql16
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $env:Path += ";$env:PGBIN"
        bash ${{ github.action_path }}/setup_db.sh
