name: "Set up postgres (windows)"
description: "Set up postgres service on windows vm for dbt integration tests"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        choco upgrade postgresql16 \
          --params "/Password:password" \
          --ia "--enable-components server,commandlinetools --extract-only 1" \
          --no-progress

        PG_BINDIR=$("$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe" --bindir)
        PG_LIBDIR=$("$PROGRAMFILES/PostgreSQL/16/bin/pg_config.exe" --libdir)

        echo "PG_BINDIR:$PG_BINDIR"
        echo "PG_LIBDIR:$PG_LIBDIR"

        echo "$PG_BINDIR" >> $GITHUB_PATH
        echo "PQ_LIB_DIR=$PG_LIBDIR" >> $GITHUB_ENV

        PGBIN=$PG_BINDIR
        PGROOT=$(dirname $PG_BINDIR)
        PGDATA="$PGROOT/data"

        echo "PGBIN=$PGBIN" >> $GITHUB_ENV
        echo "PGROOT=$PGROOT" >> $GITHUB_ENV
        echo "PGDATA=$PGDATA" >> $GITHUB_ENV

        echo "PGROOT:$PGROOT"
        ls $PGROOT

        echo "PGBIN:$PGBIN"
        # ls $PGBIN

        echo "PGDATA:$PGDATA"
        mkdir $PGDATA

        echo "registering service using $PGBIN/pg_ctl.exe"
        "$PGBIN/pg_ctl.exe" register -N "postgresql16" -D "$PGDATA" -S auto
    - shell: pwsh
      run: |
        $installerArgs = @("--install_runtimes 0", "--superpassword root", "--enable_acledit 1", "--unattendedmodeui none", "--mode unattended")
        Install-Binary `
            -Url "https://get.enterprisedb.com/postgresql/postgresql-16.1-1-windows-x64.exe" `
            -InstallArgs $installerArgs `
            -ExpectedSignature (Get-ToolsetContent).postgresql.signature

        Get-Service -Name postgresql*

        $pgReady = Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $exitCode = $pgReady.ExitCode
        if ($exitCode -ne 0) {
            Write-Host -Object "PostgreSQL is not ready. Exitcode: $exitCode"
            exit $exitCode
        }

        $pgService = Get-Service -Name postgresql16
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        # Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
        $env:Path += ";$env:PGBIN"
        bash ${{ github.action_path }}/setup_db.sh
