version: 2
jobs:
  unit:
    docker:
      - image: python:3.6
      - image: postgres
        environment: &pgenv
          POSTGRES_USER: "root"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "dbt"
    steps:
      - checkout
      - run: apt-get update && apt-get install -y python-dev python3-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run: bash test/setup_db.sh
      - run: tox -e pep8,unit-py27,unit-py36
  integration-postgres-py36:
    docker:
      - image: python:3.6
      - image: postgres
        environment: *pgenv
    steps:
      - checkout
      - run: apt-get install -y python3-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run: chown -R $(id -nu):$(id -ng) /root/
      - run: bash test/setup_db.sh
      - run:
          name: Run tests
          command: tox -e integration-postgres-py36
  integration-snowflake-py36:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: apt-get install -y python3-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-snowflake-py36
  integration-redshift-py36:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: apt-get install -y python3-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-redshift-py36
  integration-bigquery-py36:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: apt-get install -y python3-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-bigquery-py36
  integration-postgres-py27:
    docker:
      - image: python:2.7
      - image: postgres
        environment: *pgenv
    steps:
      - checkout
      - run: apt-get install -y python-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run: bash test/setup_db.sh
      - run:
          name: Run tests
          command: tox -e integration-postgres-py27
  integration-snowflake-py27:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: apt-get install -y python-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-snowflake-py27
  integration-redshift-py27:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: apt-get install -y python-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-redshift-py27
  integration-bigquery-py27:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: apt-get update && apt-get install -y python-dev
      - run: echo 127.0.0.1 database | tee -a /etc/hosts
      - run: pip install virtualenvwrapper tox
      - run:
          name: Run tests
          command: tox -e integration-bigquery-py27

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      # - integration-snowflake-py36
      # - integration-snowflake-py27
      - integration-postgres-py36
      # - integration-postgres-py27
      # - integration-redshift-py36
      # - integration-redshift-py27
      # - integration-bigquery-py36
      - integration-bigquery-py27
