name: 🛠️ Implementation
description: This is an implementation ticket intended for use by the maintainers of dbt-core
title: "[<project>] <title>"
labels: ["user_docs"]
body:
  - type: markdown
    attributes:
      value: This is an implementation ticket intended for use by the maintainers of dbt-core
  - type: checkboxes
    attributes:
      label: Housekeeping
      description: >
        A couple friendly reminders:
          1. Remove the `user_docs` label if the scope of this work does not require changes to https://docs.getdbt.com/docs: no end-user interface (e.g. yml spec, CLI, error messages, etc) or functional changes
          2. Link any blocking issues in the "Blocked on" field under the "Core devs & maintainers" project.
      options:
        - label: I am a maintainer of dbt-core
          required: true
  - type: textarea
    attributes:
      label: Short description
      description: |
        Describe the scope of the ticket, a high-level implementation approach and any tradeoffs to consider
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance critera
      description: |
        What is the definition of done for this ticket? Include any relevant edge cases and/or test cases
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: |
        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes, Notion docs as appropriate
          validations:
      required: false
