# **what?**
# Open an issue in docs.getdbt.com when a PR is labeled `user docs`

# **why?**
# To redice barriers for keeping docs up to date

# **when?**
# When a PR is labeled `user docs` and merged


name: Open issues in docs.getdbt.com repo when a PR is labeled
run-name: "Open an issue in docs.getdbt.com when a merged PR has label user docs"

on:
  pull_request:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    issues: write # opens new issues
    pull-requests: write # comments on PRs


jobs:
  generate_body:
    if: contains( github.event.pull_request.labels.*.name, 'user docs') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
        issue_body: ${{ steps.set_body.outputs.body }}
    steps:
      - name: Get issue title
        id: set_body
        run: |
          echo "body=At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page would you like to see updated." >> $GITHUB_OUTPUT

  open_issues:
    needs: [generate_body]
    uses: dbt-labs/actions/.github/workflows/open-issue-in-repo.yml@er/docs-issue
    with:
        issue_repository: "dbt-labs/docs.getdbt.com"
        issue_title: "This is my title"
        issue_labels: "content,improvement"
        issue_body: "${{needs.generate_body.outputs.issue_body }}"
    secrets: inherit
