# **what?**
# This workflow will generate a series of docker images for dbt and push them to the github container registry
#
# **why?**
# Docker images for dbt are used in a number of important places throughout the dbt ecosystem.
# This is how we keep those images up-to-date.
#
# **when?**
# This is triggered manually
name: Docker release

permissions:
  packages: write

on:
  workflow_dispatch:
    inputs:
      package:
        description: The package to release. _One_ of [dbt-core, dbt-redshift, dbt-bigquery, dbt-snowflake, dbt-spark, dbt-postgres]
        required: true
      version_number:
        description: The release version number (i.e. 1.0.0b1). Do not include `latest` tags or a leading `v`!
        required: true

jobs:
  version_metadata:
    name: Get version metadata
    runs-on: ubuntu-latest
    outputs:
      fully_qualified_tags: ${{ steps.tags.outputs.fully_qualified_tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get the tags to publish
        id: tags
        uses: ./.github/actions/latest-wrangler
        with:
          package: ${{ inputs.package }}
          new_version: ${{ inputs.version_number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  setup_image_builder:
    name: Set up Docker image builder
    runs-on: ubuntu-latest
    needs: [get_version_meta]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

  build_and_push:
    name: Build images and push to GHCR
    runs-on: ubuntu-latest
    needs: [setup_image_builder, version_metadata]
    steps:
      - name: Get docker build arg
        id: build_arg
        run: |
          BUILD_ARG_NAME=$(echo ${{ inputs.package }} | sed 's/\-/_/g')
          BUILD_ARG_VALUE=$(echo ${{ inputs.package }} | sed 's/postgres/core/g')
          echo "name=$BUILD_ARG_NAME" >> $GITHUB_OUTPUT
          echo "value=$BUILD_ARG_VALUE" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push `${{ inputs.package }}:${{ tag }}`
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          push: True
          target: ${{ inputs.package }}
          build-args: ${{ steps.build_arg.outputs.name }}_ref=${{ steps.build_arg.outputs.value }}@v${{ inputs.version_number }}
          tags: ${{ needs.version_metadata.outputs.fully_qualified_tags }}
