# **what?**
# Clean up the release prep branches and the branches generated when cutting a
# release.  Also cleanup all draft releases.

# **why?**
#

# **when?**
# Mainly on a schedule of 9:00, 13:00, 18:00 UTC everyday.
# Manual trigger can also test on demand

name: Release branch scheduled testing

on:
  schedule:
    - cron: '0 12 * * SAT' # At 12:00 on Saturday.

  workflow_dispatch: # for manual triggering

permissions:
  contents: write

jobs:
  cleanup-repo:
    uses: dbt-labs/actions/.github/workflows/release-cleanup.yml@main
    secrets: inherit
