# This is a workflow to run our unit and integration tests

name: Integration Tests

# Triggers
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: 
      - 'develop' 
      - '*.latest' 
      - 'pr/*'
      - 'releases/*'
  pull_request_target:  
    branches: [ develop ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  UnitTest:
    runs-on: 'windows-latest'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: '3.7'
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: 'x64'

    - name: 'Install dependencies'
      run: python -m pip install --upgrade pip && pip install tox
      
    - name: 'Run unit tests'
      run: python -m tox -e py -- -v
      
