

# **what?**
# Checks that a file has been committed under the /tests/unit directory
# as modification/addition to unit test.
# This workflow runs on pull_request_target because it requires
# secrets to post comments.

# **why?**
# Gentle nudge to think about adding unit tests for new code.
# It also makes sure that we can filter PRs by tag to find out what type of changes are hard to unittest.

# **when?**
# This will run for all PRs going into main.  It will
# run when they are opened, reopened, when any label is added or removed
# and when new code is pushed to the branch.  The action will then get
# skipped if the 'Hard to Unit Test' label or the 'Unit Test Not Needed' Label is present.

name: Check Changelog Entry

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main
    paths: ['core/dbt']

  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: write

jobs:
  unittest:
    name: Check if Unit Test being added.
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Unit Test Not Needed') && !contains(github.event.pull_request.labels.*.name, 'Hard to Unit Test')}}

    uses: dbt-labs/actions/.github/workflows/check-change-and-comment.yml@main
    with:
      comment: "Thank you for your pull request! We could not find a unittest file for this change. Please consider adding some. If it is hard to unittest, please add the 'Hard to Unit Test' label. If unit tests are not needed, please add the 'Unit Test Not Needed' label."
      path_filter: 'tests/unit/**'
